// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnkVcxyuV7jXokKfiKTtO--x9HXKmU6Qw',
    appId: '1:935384851011:web:a8b1ad7c94216ce8acaaf6',
    messagingSenderId: '935384851011',
    projectId: 'flutter-base-c5aab',
    authDomain: 'flutter-base-c5aab.firebaseapp.com',
    storageBucket: 'flutter-base-c5aab.firebasestorage.app',
    measurementId: 'G-8TEB6T5MTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE65M_rNBm3qSKSV45_-WOFkjcxcg_hYg',
    appId: '1:935384851011:android:5762ef94bd5973a3acaaf6',
    messagingSenderId: '935384851011',
    projectId: 'flutter-base-c5aab',
    storageBucket: 'flutter-base-c5aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx22NWSRxiVoZtPr47_VZivlArYOoLCMk',
    appId: '1:935384851011:ios:ab42f976c9bc7f71acaaf6',
    messagingSenderId: '935384851011',
    projectId: 'flutter-base-c5aab',
    storageBucket: 'flutter-base-c5aab.firebasestorage.app',
    iosBundleId: 'com.example.aiMealPlanner',
  );

}